export const CURRENCIES = [
  { code: "INR", label: "INR - Indian Rupee" },
  { code: "USD", label: "USD - US Dollar" },
  { code: "EUR", label: "EUR - Euro" },
  { code: "GBP", label: "GBP - British Pound" },
  { code: "JPY", label: "JPY - Japanese Yen" },
  { code: "CAD", label: "CAD - Canadian Dollar" },
  { code: "AUD", label: "AUD - Australian Dollar" },
  { code: "CNY", label: "CNY - Chinese Yuan" },
  { code: "CHF", label: "CHF - Swiss Franc" },
  { code: "SEK", label: "SEK - Swedish Krona" },
  { code: "NOK", label: "NOK - Norwegian Krone" },
  { code: "NZD", label: "NZD - New Zealand Dollar" },
  { code: "MXN", label: "MXN - Mexican Peso" },
  { code: "SGD", label: "SGD - Singapore Dollar" },
  { code: "HKD", label: "HKD - Hong Kong Dollar" },
  { code: "KRW", label: "KRW - South Korean Won" },
  { code: "TRY", label: "TRY - Turkish Lira" },
  { code: "ZAR", label: "ZAR - South African Rand" },
  { code: "BRL", label: "BRL - Brazilian Real" },
  { code: "AED", label: "AED - UAE Dirham" },
  { code: "PLN", label: "PLN - Polish Zloty" },
  { code: "THB", label: "THB - Thai Baht" },
  { code: "IDR", label: "IDR - Indonesian Rupiah" },
  { code: "PHP", label: "PHP - Philippine Peso" },
  { code: "VND", label: "VND - Vietnamese Dong" },
];
